### ISSUE TITLE
How can we represent quaternion in A?

### ISSUE THREAD

**Issue by tasbolat1** [utiasSTARS/bingham-rotation-learning#8]
Very interesting work!
Given A_vec, using your work we can represent quaternions, but how about vice verse? Given quaternions, can we get A_vec?

**Comment by mattgiamou** [comment]
Since the mapping from our representation $\mathbf{A}$ to $\mathrm{SO}(3)$ is surjective but not injective (see Theorem 1 in [our paper](http://www.roboticsproceedings.org/rss16/p007.html)), there is no unique choice of $\mathbf{A} \in \mathbb{S}_\lambda^4$ corresponding to a particular $\mathbf{q} \in S^3$. 

The most parsimonious choice, as suggested by our proof of Theorem 1, is probably the outer product $\mathbf{A} = \mathbf{I} - \mathbf{q} \mathbf{q}^T$, where $\mathbf{I}$ is the identity matrix. 

Hope this helps!
